server:
  port: 9090
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: producer-service
          uri: lb://producer-service/
          predicates: 
            - Path=/producer/**
        - id: consumer-service
          uri: lb://consumer-service/
          predicates:
            - Path=/consumer/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance: 
    preferIpAddress: true